### ISSUE TITLE
transaction problem in buy zksyncpad live sell token.

### ISSUE THREAD

**Issue by Kazirony90** [bxpana/zkSync-Tips#10]
hello sir, I participated in ZKSYNCPAD live sell with 0.1 zksync eth. But 0.1 zksync eth has been deducted from my account. But when I go to Zksync explorer it shows only verifying loading and I don't get any zksyncpad token. Now please solve my problem. I believe a lot in the Zksync project. Give me the opportunity to always be by your side by solving my problems. Below is my transaction hash.

this is my zksync address in metamask wallet: 0x68d556831807FA9916812e8C16a7adAfc64eB29c

transaction hash: 0x0e1537f8e4067933aed5af115a7cbbd43842f3efd2bd62a9cee39b611ae23d29

commit tx hash: 0xb432b37cf2bfc9a9ed9167b16ff7ccbc9ee9a3b60b4b4f6c4fb1557fa5916f7a

prove tx hash: 0x5538fb64577bb3c76a94a4087a203077a4ecdfeb36ff25c976db764c47d081e6
![Uploading Capture.PNGdee.PNG…]()

**Comment by bxpana** [comment]
@Kazirony90 The zkSync Team does not have any affiliation with ZKSYNCPAD and you would want to reach out to their team for any support.
