### ISSUE TITLE
transaction failed

### ISSUE THREAD

**Issue by Kathi-cloud** [bxpana/zkSync-Tips#5]
![Screenshot (8)](https://user-images.githubusercontent.com/74136142/227809664-907aa84a-4a45-43f4-b0b2-cc59d72b179b.png)

similar problem?
metamask warned, that the chain is crowded?
transaction failed

maybe, the same issue, you had?

**Comment by Kathi-cloud** [comment]
> ![Screenshot (8)](https://user-images.githubusercontent.com/74136142/227809664-907aa84a-4a45-43f4-b0b2-cc59d72b179b.png)
> 
> similar problem? metamask warned, that the chain is crowded? transaction failed
> 
> maybe, the same issue, you had?

0x74f269b4fc316a6257b7d52552645f0a99fd71e4ff90894891b2277d24ebff93
transacion ID

**Comment by Kathi-cloud** [comment]
![Screenshot (9)](https://user-images.githubusercontent.com/74136142/227810029-00ec5250-9624-4869-8b56-68b2945316a4.png)

**Comment by bxpana** [comment]
This should be resolved now. Feel free to open another issue if you are still having issues
