### ISSUE TITLE
Withdrawal tokens not reflecting in other wallet

### ISSUE THREAD

**Issue by nykrohith** [bxpana/zkSync-Tips#8]
I had withdrawn my tokens from L2 to L1. zKsync has given confirmation but my tokens are not reflecting in the BNB L1 wallet.  In Etherscan it is not showing any transaction hash. Kindly look into the issue and resolve it asap. I had transferred a bit high volume so requesting team to work on it and do the needful and get my tokens back.

**Comment by bxpana** [comment]
> I had withdrawn my tokens from L2 to L1. zKsync has given confirmation but my tokens are not reflecting in the BNB L1 wallet. In Etherscan it is not showing any transaction hash. Kindly look into the issue and resolve it asap. I had transferred a bit high volume so requesting team to work on it and do the needful and get my tokens back.

It sounds like you used a third party bridge so you would want to reach out to the project you used to bridge to get an update

**Comment by nykrohith** [comment]
Hi bxpana what can i do next to get it back kindly tell me the solution for this.

**Comment by nykrohith** [comment]
Had been hospitalized could not replay you back.

**Comment by bxpana** [comment]
@nykrohith I'm sorry to hear that and hope you are doing ok. The solution would be to reach out to the bridge you used to move your funds so they can look into it.

**Comment by nykrohith** [comment]
I'm Good & Thanks for the concern. Will reach out to the bridge and seek out for help.
